language: go
go:
    - 1.7
    - 1.8

before_install:
  - go get github.com/mattn/goveralls

script:
 - go test -v ./...
 - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  email:
    on_success: never
    on_failure: never